#!/bin/sh

eval PATH=$NIMBLE/bin:$PATH

echo "---------- Compile"
echo nim compile -o:a.out $@
nim compile -o:a.out $@

if [ $? -ne 0 ]; then
    exit 1
fi

echo "---------- Run Test"
echo oj test
oj test
