version: "3"

services:
  judge:
    build: './judge'
    image: te-sh/procon-judge
    container_name: projdg
    volumes:
      - './codes:/codes'
    tty: true
  docs:
    build: './docs'
    image: te-sh/procon-docs
    container_name: prodoc
    volumes:
      - './docs:/docs'
    ports:
      - '4000:4000'
