version: "3"

services:
  judge:
    build:
      context: './judge'
      args:
        SITES: atcoder yukicoder codeforces
        DMD_ATCODER: dmd-2.091.0
        DMD_BINDIR_ATCODER: linux/bin64
        DMD_LIBDIR_ATCODER: linux/lib64
        DMD_OPTION_ATCODER: -m64 -of=a.out
        DMD_YUKICODER: dmd-2.095.1
        DMD_BINDIR_YUKICODER: linux/bin64
        DMD_LIBDIR_YUKICODER: linux/lib64
        DMD_OPTION_YUKICODER: -m64 -of=a.out
        DMD_CODEFORCES: dmd-2.086.0
        DMD_BINDIR_CODEFORCES: linux/bin64
        DMD_LIBDIR_CODEFORCES: linux/lib32
        DMD_OPTION_CODEFORCES: -m32 -fPIC -defaultlib=libphobos2.so -of=a.out
    image: te-sh/procon-judge
    container_name: projdg
    volumes:
      - './codes-d:/codes-d'
      - './codes-nim:/codes-nim'
      - './codes-crystal:/codes-crystal'
    tty: true
  docs:
    build:
      context: './docs'
    image: te-sh/procon-docs
    container_name: prodoc
    volumes:
      - './docs:/docs'
    ports:
      - '4000:4000'
