;; d-mode
(add-hook 'd-mode-hook
	  (lambda ()
	    (disable-indent-tabs-mode)
	    (setup-flycheck-d-unittest)
	    (flycheck-dmd-dub-set-variables)))

;; Copy buffer to submit
(defun d-copy-for-submit ()
  (interactive)
  (let ((old-buf (current-buffer)))
    (cl-flet* ((delete-line () (delete-region (line-beginning-position) (+ (line-end-position) 1)))
               (search-and-remove (x) (if (search-forward x nil t) (delete-line))))
      (with-temp-buffer
        (insert-buffer-substring old-buf)
        (goto-char (point-min))
        (while (re-search-forward "^\\(version(unittest)\\|// \\(path\\|url\\):\\)" nil t)
          (delete-line)
          (delete-blank-lines)
          (goto-char (point-min)))
        (search-forward "void main()")
        (let ((rdsp (count-matches "rdsp"))
              (pick (count-matches "pick("))
              (pickv (count-matches "pickV("))
              (readv (count-matches "readV("))
              (reada (count-matches "readA("))
              (readm (count-matches "readM("))
              (readc (count-matches "readC("))
              (reads (count-matches "readS("))
              (writea (count-matches "writeA(")))
          (goto-char (point-min))
          (if (eq (+ rdsp readv reada readm readc reads) 0)
              (search-and-remove "rdsp("))
          (if (eq (+ pick pickv readv reada readm readc reads) 0)
              (search-and-remove "pick("))
          (if (eq pickv 0)
              (search-and-remove "pickV("))
          (if (eq readv 0)
              (search-and-remove "readV("))
          (if (eq (+ reada readm) 0)
              (search-and-remove "readA("))
          (if (eq readm 0)
              (search-and-remove "readM("))
          (if (eq readc 0)
              (search-and-remove "readC("))
          (if (eq reads 0)
              (search-and-remove "readS("))
          (if (eq writea 0)
              (search-and-remove "writeA(")))
        (clipboard-kill-ring-save (point-min) (point-max))))))

;; yasnippet
(require 'yasnippet)
(setq yas-snippet-dirs (append yas-snippet-dirs
			       '("~/projects/procon2/emacs/snippets")))
(yas-global-mode 1)
