# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 競技プログラミングメモ
baseurl: /procon2
description: 競技プログラミングメモ

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .gitignore
  - Dockerfile
  - Gemfile
  - Gemfile.lock

# Default settings
collections:
  yuk:
    output: true
  atc:
    output: true
  cdf:
    output: true

defaults:
  - scope:
      path: ""
      type: yuk
    values:
      layout: problem
      subtitle: yukicoder
  - scope:
      path: ""
      type: atc
    values:
      layout: problem
      subtitle: AtCoder
  - scope:
      path: ""
      type: cdf
    values:
      layout: problem
      subtitle: CodeForces
